### PR TITLE
Upstream release

### PR DESCRIPTION
**Pull request by jbweston**
Followup from #61 

Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Reset the build number to `0` (if the version changed)
* [x] Ensured the license file is being packaged.
* [x]  Set the upstream tarball URL to Kwant website or PyPI (only possible after official tag and release)

### CODE REVIEW

**Comment by jbweston** [comment]
It says the builds were successful, but it's a lie: they're failing because `kwant/tests/test_qsymm` is being run

**Comment by jbweston** [comment]
Seems to work!

**Comment by akhmerov** [comment]
How come it works on py37 even with sympy pinned and not being available?

**Comment by jbweston** [comment]
I can't see any 3.7 yet. Probably I forgot to rerender or sth

**Comment by jbweston** [comment]
@conda-forge-admin please re-render

**Comment by basnijholt** [comment]
@conda-forge-admin please re-render

**Pull request merged**
