### PR TITLE
Build for Python 3.10

### PR DESCRIPTION
**Pull request by basnijholt**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Changes taken from https://github.com/conda-forge/kwant-feedstock/pull/93

### CODE REVIEW

**Comment by basnijholt** [comment]
@conda-forge-admin, please rerender

**Comment by basnijholt** [comment]
@akhmerov, you pinned both Matplotlib and Sympy in https://github.com/conda-forge/kwant-feedstock/pull/89.

It is not clear to me why exactly.

I removed the innings here to try to see whether the builds will pass.

**Comment by basnijholt** [comment]
@akhmerov, thanks for fixing 14.3! I have updated this PR.

**Comment by basnijholt** [comment]
@conda-forge-admin, please rerender

**Comment by akhmerov** [comment]
OK, this new failure is an absolute mystery :sweat_smile:

**Comment by basnijholt** [comment]
Hopefully, it goes away when restarting the CI 🥲

**Pull request merged**
