### PR TITLE
update version to 1.4.0

### PR DESCRIPTION
**Pull request by akhmerov**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by akhmerov** [comment]
@conda-forge-admin please rerender

**Comment by akhmerov** [comment]
Azure pipelines `linux_python3.7` shows a failed test, but reports a build success. @basnijholt any idea why?

**Comment by akhmerov** [comment]
All the linux (both azure and circleci) show a `qsymm` test failing. This raises two issues:

- Why do the pipelines show that they succeeded?
- Why does the test actually fail?

Marking as WIP.

**Comment by basnijholt** [comment]
@akhmerov could it be that https://github.com/conda-forge/kwant-feedstock/blob/master/recipe/run_test.py doesn't correctly raise the error code?

**Comment by akhmerov** [comment]
Indeed. Directly invoking `pytest -x -v` does exit with a correct error code.

**Pull request merged**
