### PR TITLE
support py39

### PR DESCRIPTION
**Pull request by akhmerov**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* ~~[ ] Reset the build number to `0` (if the version changed)~~
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by akhmerov** [comment]
@conda-forge-admin, please rerender

**Comment by basnijholt** [comment]
Not sure why a new build is necessary but go ahead with merging. 👍

**Comment by akhmerov** [comment]
This is to compile for Python 3.9, however the build is failing. I didn't actually notice I was requesting a review.

**Comment by akhmerov** [comment]
@conda-forge-admin, please rerender

**Comment by akhmerov** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
