### PR TITLE
WIP: windows support

### PR DESCRIPTION
**Pull request by jbweston**
Kwant now does not need to be linked against Lapack because it can use scipy's Lapack.

### CODE REVIEW

**Comment by basnijholt** [comment]
I think you need to re-render again because now the builds are skipping.

**Comment by jbweston** [comment]
@basnijholt how do you force it to use Python 3? I really don't understand because we have `skip: True  # [py2k]`

**Comment by basnijholt** [comment]
You need to do the re-render *after* you change the `meta.yml` file.

**Comment by jbweston** [comment]
yes, Bas, I did; you can see this from the commit history

**Comment by basnijholt** [comment]
Oh, I see it yes, was confused about it because GitLab shows the commits in the opposite order.

I think it should work now.

**Comment by jbweston** [comment]
it's not grabbing the latest Kwant, somehow. `Error: BLAS/LAPACK are required but were not found` does not exist in `master`

**Comment by jbweston** [comment]
Also I should probably not remove `openblas` from all builds

**Comment by akhmerov** [comment]
Why not?

**Comment by jbweston** [comment]
because it is required by Linux builds for mumps

**Comment by akhmerov** [comment]
I see. Also for OSX I imagine.

**Comment by basnijholt** [comment]
But MUMPS is not being build here, right?

**Comment by basnijholt** [comment]
> it's not grabbing the latest Kwant, somehow. Error: BLAS/LAPACK are required but were not found does not exist in master

That is also how `conda-forge` works. You can only build tagged versions.

**Comment by jbweston** [comment]
well then it will never pass -- the relevant changes for windows are only on `master`!

**Comment by basnijholt** [comment]
numpy Windows builds: https://github.com/conda-forge/numpy-feedstock/pull/73

openBLAS is now on Windows :)

**Comment by basnijholt** [comment]
@conda-forge-admin please rerender.

**Pull request closed without merging**
