### PR TITLE
bump version to 1.2.2 for Python 3

### PR DESCRIPTION
**Pull request by basnijholt**

### CODE REVIEW

**Comment by jakirkham** [comment]
Needs a [re-rendering]( https://github.com/conda-forge/conda-smithy#re-rendering-an-existing-feedstock ).

**Comment by basnijholt** [comment]
Was just doing it :) See 9e471a9

**Comment by jakirkham** [comment]
Also would add that if you need to keep supporting `1.1.x`, I would add a branch say `1.1` on the main feedstock here where `master` is currently. That way you can keep releasing versions for Python 2 support.

**Comment by basnijholt** [comment]
Can I just make a branch directly from master?

**Comment by jakirkham** [comment]
Not sure if I understand the question, but I think the answer is yes. To elaborate a bit, I'm suggesting the following assuming that `conda-forge` is the name for this upstream repo.

```
git checkout conda-forge/master
git checkout -b 1.1
git push -u conda-forge 1.1
```

**Comment by jakirkham** [comment]
Alternatively you can use the find/create GUI on this repo to add that branch.

**Comment by jakirkham** [comment]
Looks good. So going forward `master` will be the latest version and any `1.1.x` patch releases can be PR'd against the `1.1` branch. Does that make sense?

**Comment by basnijholt** [comment]
I completely understand, thank you for all the help!

**Comment by jakirkham** [comment]
My pleasure. 😄

**Pull request merged**
