### PR TITLE
bump build number

### PR DESCRIPTION
**Pull request by basnijholt**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by basnijholt** [comment]
@conda-forge-admin, please rerender

**Comment by akhmerov** [comment]
Something with qsymm. @dvarjas does the error ring a bell?

**Comment by dvarjas** [comment]
Which version of kwant is being built here? I'm a noob, have no clue about conda-forge. kwant-1.4.1 doesn't yet have the fixes that we did with @jbweston , so no surprise if the tests don't pass for that.

**Comment by basnijholt** [comment]
So this won't pass until 1.4.2 is released? Or do we patch out the tests?

**Comment by akhmerov** [comment]
I think releasing 1.4.2 instead of patching the tests is a good idea.

**Pull request closed without merging**
