### PR TITLE
add a build variant that links Kwant against mumps-mpi

### PR DESCRIPTION
**Pull request by basnijholt**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by basnijholt** [comment]
@conda-forge-admin, please rerender

**Comment by jbweston** [comment]
@conda-forge-admin, please rerender

**Comment by jbweston** [comment]
All the tests now pass, but when I manually install kwant and fenics together in the same environment fenics gives all sorts of warnings on import about integer size mismatches.

**Comment by akhmerov** [comment]
Do you think these warnings indicate that things are broken?

**Comment by jbweston** [comment]
> Do you think these warnings indicate that things are broken?

Yes, but I don't know what it is exactly. I suspect that it is due to a difference in compile-time and run-time versions of MPI.

**Comment by basnijholt** [comment]
Great work Joe!

I say, let's go ahead and merge 👍

**Comment by akhmerov** [comment]
A quick question. If a user writes `mamba install kwant` in a fresh env, which variant is installed? Can we select a default?

**Comment by basnijholt** [comment]
The default will be the `nompi`, this is because we set the build number lower, so the default stays the same.

If someone prefers the mpi version, one should specify: `conda install "kwant=*=*mpi"`.

**Comment by akhmerov** [comment]
Ah, I see that now. Neat! Please add a comment around that line to explain the purpose of the build number bump.

Given that I'm :+1: on merging, but I'd like @jbweston's confirmation.

**Comment by jbweston** [comment]
We can't merge because things are still broken!

For clarity here's what happens when I `import fenics` in an environment where the mpi variant of kwant is installed:
image


@basnijholt also, as our variants are named `nompi` and `mpi` I think this means if we want the mpi variant we have to specify `kwant=*=*_mpi` with a weird leading underscore. This is because `kwant=*=*mpi` will also match `nompi`.

**Comment by basnijholt** [comment]
@conda-forge-admin, please rerender

**Comment by jbweston** [comment]
> @jbweston, this seems unrelated to the changes made here.
> 
> Try installing the current version of kwant in Python 3.9 to get the same warnings.

Indeed, `conda create -n fenics-alone -c conda-forge fenics; conda activate fenics-alone; python -c 'import fenics'` gives these warnings, so it's not us.

**Pull request merged**
