### PR TITLE
WIP: link Kwant against MUMPS on Windows

### PR DESCRIPTION
**Pull request by jbweston**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)

### CODE REVIEW

**Comment by jbweston** [comment]
Even though the tests pass the mumps tests are still skipped.

**Comment by jbweston** [comment]
@conda-forge-admin please re-render

**Comment by jbweston** [comment]
I think we might have hit an impasse again:

+ Building using Visual Studio compiler complains that there is no `libzmumps.lib`. Inspecting the `mumps-seq` files it seems that indeed there are only DLL and header files distributed, no `.lib`. This may be because `mumps-seq` is built with MinGW and not visual studio

+ Building using MinGW compiler fails with "cannot fine `-lmsvcr140`. Seems that this library has been replaced by another one, and the only way to remove this from the link line and replace it with the correct library is to alter the Cython source code? https://stackoverflow.com/questions/52943590/cython-missing-msvcr140-dll

**Comment by akhmerov** [comment]
@conda-forge-admin, please rerender

**Comment by jbweston** [comment]
This branch is very old; we might try to do this again in a new PR.

**Pull request closed without merging**
